### ISSUE TITLE
error when binding port 60001 to 0.0.0.0, this port is occupied. 

### ISSUE THREAD

**Issue by briup1** [jina-ai/simple-jina-examples#7]
always get this error

**Comment by briup1** [comment]
python app.py 
⠋ 0/3 waiting executor0 executor1 gateway to be ready...           JINA@5220[E]:error when binding port 60001 to 0.0.0.0, this port is occupied. If you are using Linux, try `lsof -i :60001` to see which process occupies the port.
        gateway@5220[E]:ZMQError('Address already in use') during <class 'jina.peapods.runtimes.gateway.grpc.GRPCRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/peas/__init__.py", line 79, in run
    runtime = runtime_cls(
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/asyncio.py", line 60, in __init__
    self._loop.run_until_complete(self.async_setup())
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/runtimes/gateway/grpc/__init__.py", line 44, in async_setup
    self.zmqlet = AsyncZmqlet(self.args, logger=self.logger)
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/zmq/__init__.py", line 79, in __init__
    ) = self._init_sockets()
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/zmq/__init__.py", line 248, in _init_sockets
    raise ex
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/zmq/__init__.py", line 191, in _init_sockets
    in_sock, in_addr = _init_socket(
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/jina/peapods/zmq/__init__.py", line 879, in _init_socket
    sock.bind(f'tcp://{host}:{port}')
  File "/zhangxuejie373/anaconda3/envs/p38_paddle/lib/python3.8/site-packages/zmq/sugar/socket.py", line 214, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
           JINA@5218[E]:error when binding port 60001 to 0.0.0.0, this port is occupied. If you are using Linux, try `lsof -i :60001` to see which process occupies the port.
           JINA@5219[E]:error when binding port 60001 to 0.0.0.0, this port is occupied. If you are using Linux, try `lsof -i :60001` to see which process occupies the port.
      executor0@5218[E]:ZMQError('Address already in use') during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details

**Comment by JoanFM** [comment]
have u run as suggested?

`lsof -i :60001` to see which PID is occupying the port?
